export const SAP_MODULES: Record<string, string> = {
  FI: 'Financial Accounting',
  CO: 'Controlling',
  SD: 'Sales & Distribution',
  MM: 'Materials Management',
  PP: 'Production Planning',
  PM: 'Plant Maintenance',
  QM: 'Quality Management',
  HR: 'Human Resources',
  PS: 'Project System',
  RE: 'Real Estate',
  TR: 'Treasury',
  BC: 'Basis Components',
  CA: 'Cross-Application',
  LO: 'Logistics General',
  LE: 'Logistics Execution',
  WM: 'Warehouse Management',
  EWM: 'Extended Warehouse Management',
  TM: 'Transportation Management',
  AP: 'Accounts Payable',
  AR: 'Accounts Receivable',
  AM: 'Asset Management',
  GL: 'General Ledger',
  CS: 'Customer Service',
  SM: 'Service Management',
  SRM: 'Supplier Relationship Management',
  CRM: 'Customer Relationship Management',
  SCM: 'Supply Chain Management',
  PLM: 'Product Lifecycle Management',
  IS: 'Industry Solutions',
  BW: 'Business Warehouse',
  GRC: 'Governance, Risk & Compliance',
};

export function getModuleLabel(moduleCode: string): string {
  return SAP_MODULES[moduleCode.toUpperCase()] ?? moduleCode;
}

export const FUNCTIONAL_AREA_TO_MODULE: Record<string, string> = {
  'FI-GL': 'FI',
  'FI-AP': 'FI',
  'FI-AR': 'FI',
  'FI-AA': 'FI',
  'FI-TV': 'FI',
  'CO-CCA': 'CO',
  'CO-PA': 'CO',
  'CO-PC': 'CO',
  'CO-OM': 'CO',
  'SD-SLS': 'SD',
  'SD-BIL': 'SD',
  'SD-CAS': 'SD',
  'MM-PUR': 'MM',
  'MM-IV': 'MM',
  'MM-IM': 'MM',
  'PP-SFC': 'PP',
  'PP-MRP': 'PP',
  'HR-PA': 'HR',
  'HR-PY': 'HR',
  'HR-PT': 'HR',
};
